### ISSUE TITLE
second outpu order of letters wrong

### ISSUE THREAD

**Issue by Krigsgaldr793** [ParisNeo/Gpt4All-webui#8]
The first request is doing good but if i am  trying to continue the conversation it looks like this:

use he ecatno ura dho eit ticsaefterohsatse

**Comment by ParisNeo** [comment]
Thank you for the remark. I think I have an idea about the source of the problem. I'll repare it right away and then I'll notify you.

**Comment by ParisNeo** [comment]
Done,

I have made some nice changes to the UI. Now you can talk as much as you want with it
